### ISSUE TITLE
SB2CS_TYPES doesn't contain WITHDRAWAL

### ISSUE THREAD

**Issue by TAQ2** [chernals/swissborg_to_coinstats#1]
Not sure how you would deal with this type of transaction however sometimes the `Type` is `Withdrawal`

**Comment by chernals** [comment]
Should be done now ;)

My SB account is quite new so didn't have that when I tested it.

**Comment by TAQ2** [comment]
How are you anticipating dealing with a withdrawal? Just ignoring it I assume?

**Comment by chernals** [comment]
That's the whole issue with the way CS calculates the PNL, but I would say it's a different topic.

Transactions can be of type 'withdrawal' in the CS CSV file. Now it should work that way. What CS will do with that is a different story.

Unless I missed something.

**Comment by TAQ2** [comment]
woow so from my findings in an example where I buy 1 btc then withdraw half a btc- coinstats will just give me one transaction of I bought 0.5 btc. Not sure if that's correct or not but as you say this is a coinstats decision

**Comment by TAQ2** [comment]
I guess it depends what each person needs but in my case I'll be removing any withdrawal rows from my swissborg excel file

**Comment by chernals** [comment]
I could make it an option to the script to remove certains lines : remove withdrawals, remove earnings, etc.

**Comment by TAQ2** [comment]
Up to you, I'd say just put it as a disclaimer on the readme.

I'll close this issue since the original problem has been solved. Feel free to reopen if you want to :)
