### ISSUE TITLE
USD is hardcoded

### ISSUE THREAD

**Issue by TAQ2** [chernals/swissborg_to_coinstats#2]
You can probably use the local currency (Cell B4) to make this dynamic

**Comment by chernals** [comment]
That's what I think as well.

I hope coinstats will pick it up, however, I read on their feedback page that it's been in the pipeline for 4 months now...

I guess there are a few more bugs in there, as we go along and fix them I'll remove the CSV support altogether.

**Comment by TAQ2** [comment]
😭  they have such a nice interface yet a horrible engine

**Comment by TAQ2** [comment]
@chernals you left the filename hardcoded on line 43 :)

**Comment by TAQ2** [comment]
also you need to pass its value into calculate_fee

**Comment by chernals** [comment]
Thanks for the PR. SHould be all good now.
